version: "2.2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
  db:
    hostname: localhost
    image: genschsa/mysql-employees:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: employees